removed Unused variables
PrimeDAO/launch-contracts pull request #40
Opened 2022-04-19 10:12 UTC by decadanse

2022-04-20 17:26 UTC, arseneeth requested changes
needs changes

2022-04-20 17:26 UTC, arseneeth commented on contracts/seed/Seed.sol
> +                    // (seedRequired * _classFee) / PRECISION ));
Please delete comments

2022-04-20 18:38 UTC, decadanse commented on contracts/seed/Seed.sol
> +                    // (seedRequired * _classFee) / PRECISION ));
fixed

2022-04-22 09:34 UTC, arseneeth approved these changes

2022-04-25 12:43 UTC, arseneeth approved these changes

2022-04-25 12:44 UTC, merged