33 There is no guarantee that users can buy hardCap amount of tokens
PrimeDAO/launch-contracts pull request #61
Opened 2022-04-20 18:58 UTC by decadanse

closes <https://github.com/PrimeDAO/launch-contracts/issues/33>

2022-04-25 12:54 UTC, arseneeth requested changes
I don't quite understand why this PR is only a comment update

2022-04-25 19:19 UTC, BritikovKI commented on contracts/seed/Seed.sol
> +                // So when it's reached, for others will their balance be bigger or not - doesn't matter anymore.
Nice comment

2022-04-25 19:19 UTC, BritikovKI approved these changes

2022-04-25 19:20 UTC, BritikovKI commented
> I don't quite understand why this PR is only a comment update

Because it's a feature, not a bug, comment is just a clarification here for the auditors

2022-04-26 10:20 UTC, arseneeth requested changes

2022-04-26 10:20 UTC, arseneeth commented on contracts/seed/Seed.sol
> +                // So when it's reached, for others will their balance be bigger or not - doesn't matter anymore.
*sold not selled

2022-04-27 14:13 UTC, merged