62 Withdraw the whole funding token balance when withdrawing sale proceeds
PrimeDAO/launch-contracts pull request #63
Opened 2022-04-21 14:17 UTC by decadanse

closes <https://github.com/PrimeDAO/launch-contracts/issues/62>

2022-04-25 12:52 UTC, arseneeth requested changes

2022-04-25 12:52 UTC, arseneeth commented on contracts/seed/Seed.sol
> +        uint256 toWithdraw = fundingToken.balanceOf(address(this));
Why do we create the new variable here?

2022-04-25 12:52 UTC, arseneeth commented on contracts/seed/Seed.sol
> +        fundingToken.transfer(msg.sender, toWithdraw);
we can do just `fundingToken.transfer(msg.sender, fundingToken.balanceOf(address(this));`

and add a comment on what's happening here for clarity

2022-04-25 21:02 UTC, BritikovKI approved these changes

2022-04-25 21:02 UTC, BritikovKI commented on contracts/seed/Seed.sol
> +                seedToken.safeTransfer(_refundReceiver, amountToTransfer);
Fix tabulation pls

2022-04-27 13:23 UTC, arseneeth approved these changes

2022-04-27 14:12 UTC, merged