3 contributor class structure
PrimeDAO/launch-contracts pull request #7
Opened 2022-03-14 20:01 UTC by BritikovKI

Closes #3

2022-03-15 15:06 UTC, arseneeth requested changes
changes requested

2022-03-15 15:14 UTC, BritikovKI commented on contracts/seed/Seed.sol
> +    ContributorClass[] classes; // Different contributor classes
Fixed

2022-03-15 15:14 UTC, BritikovKI commented on contracts/seed/Seed.sol
> +        uint256 cap; // Amount of tokens that can be donated by specific contributor
Fixed

2022-03-16 17:10 UTC, arseneeth approved these changes
lgtm

2022-03-17 09:57 UTC, merged